#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM rowanto/docker-java8-mvn-nodejs-npm

ADD ./PCAcert.crt /usr/local/share/ca-certificates/PCAcert.crt
RUN update-ca-certificates
RUN npm config set strict-ssl false
RUN npm install -g  n
RUN n 6.9.1
RUN npm install npm@3.10.8
RUN apt-get update -y
RUN apt-get install -y nmap
ADD run-application-dev.sh /run-application.sh
RUN chmod +x /run-application.sh

ARG user_name
ARG user_id
ARG group_id
RUN useradd -u $user_id -ms /bin/bash $user_name
RUN groupmod -g $group_id $user_name
RUN adduser $user_name sudo
RUN chown -R $user_name /usr/local/
RUN chown -R $user_name /usr/lib/
RUN chown -R $user_name /usr/bin/
USER $user_name
WORKDIR /home/$user_name
